AccessControlPortal/Controllers/PessoaTipoAcessoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using AccessControlPortal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AccessControlPortal.Controllers
{
    public class PessoaTipoAcessoController : Controller
    {
        private string Baseurl = "https://localhost:44372/";

        // GET: PessoaTipoAcesso/Create
        public async Task<ActionResult> Create(int pessoa)
        {
            //Pegar os códigos de acesso que não estão em uso:
            List<CodigoAcesso> codigosLivres = new List<CodigoAcesso>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.GetAsync("api/CodigoAcesso/GetCodigosAcessoLivres");

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                    codigosLivres = JsonConvert.DeserializeObject<List<CodigoAcesso>>(EmpResponse);

                    var model = new CriarPessoaTipoAcesso
                    {
                        IdPessoa = pessoa,
                        IdCodigoAcesso = codigosLivres.Select(x => x.Id).ToList()
                    };

                    return View(model);
                }
                else
                {
                    return View("Error");
                }
            }
        }

        // POST: PessoaTipoAcesso/Create
        [HttpPost]
        public async Task<JsonResult> Create(int idPessoa, int idTipoAcesso, Guid idCodigoAcesso)
        {
            var pessoa = new PessoaCreate();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.PostAsJsonAsync<PessoaCreate>($"api/PessoaTipoAcesso/AddPessoaTipoAcesso?idPessoa={idPessoa}&idTipoAcesso={idTipoAcesso}&idCodigoAcesso={idCodigoAcesso}", pessoa);

                if (Res.IsSuccessStatusCode)
                {
                    return Json(Url.Action("Index", "Home"));
                }
                else
                {
                    return Json(Url.Action("Error"));
                }
            }
        }

        public ActionResult BaixaNoAcesso()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> GetIdPessoaTipoAcesso(string cpf)
        {
            PessoaTipoAcesso EmpInfo = new PessoaTipoAcesso();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.GetAsync("api/PessoaTipoAcesso/GetPessoaTipoAcesso?cpf=" + cpf);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                    EmpInfo = JsonConvert.DeserializeObject<PessoaTipoAcesso>(EmpResponse);

                    var aux = this.SairDoCondominio(EmpInfo);

                    if (await aux)
                    {
                        return Json(Url.Action("Index", "Home"));
                    }
                    else
                    {
                        return Json(Url.Action("Index", "Home"));
                    }
                }
                else
                {
                    return Json(Url.Action("Error"));
                }
            }
        }

        [HttpPut]
        public async Task<bool> SairDoCondominio(PessoaTipoAcesso empInfo)
        {
            var idPessoaTipoAcesso = empInfo.Id;
            var idCodigoAcesso = empInfo.IdCodigoAcesso;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.PutAsJsonAsync<PessoaTipoAcesso>("api/PessoaTipoAcesso/UpdatePessoaTipoAcesso?idPessoaTipoAcesso=" + idPessoaTipoAcesso, empInfo);

                if (Res.IsSuccessStatusCode)
                {
                    var aux = this.UpdateStatusCartao(idCodigoAcesso);
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }

        [HttpPut]
        public async Task<bool> UpdateStatusCartao(Guid guid)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.PutAsJsonAsync<Guid>($"api/CodigoAcesso/UpdateCodigoAcesso?id={guid}&staus=false", guid);

                if (Res.IsSuccessStatusCode)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
    }
}

AccessControlPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccessControlPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AccessControlPortal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Conceder acesso a uma Pessoa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PessoaTipoAcesso" asp-action="BaixaNoAcesso">Dar baixa no acesso da pessoa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AccessControlPortal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>